[package]
name = "email-statistics-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "3.0.0-alpha.14"
native-tls = "0.2"
base64 = "0.21"